source 'https://rubygems.org/'

gem 'puma'
gem 'sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'newrelic_rpm'
gem 'redis'
gem 'hiredis'

gem 'stackprof', git: 'https://github.com/osyoyu/stackprof'

group :development do
  gem 'sinatra-contrib'
end

group :test do
  gem 'rspec'
end
